# -*- coding: utf-8 -*-
"""kMeansProjectCannonWashington.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MApKEjvNq74-QW1wX0B_nXtWVR2q-E4q
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

#Preprocessing

mallData = pd.read_csv("shopping mall.csv")


mallData.dropna(inplace=True)


X = mallData[['Annual Income', 'Spending Score']]


X.describe()

#K with Elbow Method
sse = []
for i in range(1, 11):
    km = KMeans(n_clusters=i, random_state=2)
    km.fit(X)
    sse.append(km.inertia_)


sns.set_style("whitegrid")
g=sns.lineplot(x=range(1,11), y=sse)

g.set(xlabel ="Number of cluster (k)", ylabel = "Sum Squared Error", title ='Elbow Method')

plt.show()

#Apply K-Means
kmeans = KMeans(n_clusters=3)
mallData['Cluster'] = kmeans.fit_predict(X)


cluster_summary = mallData.groupby('Cluster').mean(numeric_only=True)[['Annual Income', 'Spending Score']]
print("Cluster Summary Statistics:")
print(cluster_summary)


segment_names = {0: "Centroid 0", 1: "Centroid 1", 2: "Centroid 2"}
mallData['Segment'] = mallData['Cluster'].map(segment_names)

centroids = kmeans.cluster_centers_

plt.figure(figsize=(10, 6))
sns.scatterplot(x=X.iloc[:, 0], y=X.iloc[:, 1], hue=mallData['Cluster'], palette='viridis', style=mallData['Cluster'], legend='full')
plt.scatter(centroids[:, 0], centroids[:, 1], s=300, c='red', marker='X', label='Centroids')
plt.xlabel('Income')
plt.ylabel('Spending Score')
plt.title('K-Means Clusters with Centroids')
plt.legend()
plt.show()

cluster_summary['Segment'] = cluster_summary.index.map(segment_names)
print("Customer Segmentation Summary Table:")
print(cluster_summary)